/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 23-Mar-2024 1:20:01 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `box_subscribers` CASCADE
;

DROP TABLE IF EXISTS `boxes` CASCADE
;

DROP TABLE IF EXISTS `prayers` CASCADE
;

DROP TABLE IF EXISTS `schedules` CASCADE
;

DROP TABLE IF EXISTS `songs` CASCADE
;

DROP TABLE IF EXISTS `subscribers` CASCADE
;

/* Create Tables */

CREATE TABLE `box_subscribers`
(
	`box_subs_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`box_id` INT UNSIGNED NOT NULL,
	`subs_id` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_box_subscribers` PRIMARY KEY (`box_subs_id` ASC)
)

;

CREATE TABLE `boxes`
(
	`box_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`box_name` VARCHAR(50) NOT NULL,
	`prayer_id` INT UNSIGNED NOT NULL,
	`enabled` BOOL NOT NULL DEFAULT 1,
	CONSTRAINT `PK_Box` PRIMARY KEY (`box_id` ASC)
)

;

CREATE TABLE `prayers`
(
	`prayer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`prayer_name` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_box_parayers` PRIMARY KEY (`prayer_id` ASC)
)

;

CREATE TABLE `schedules`
(
	`schedule_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`prayer_id` INT UNSIGNED NOT NULL,
	`date` DATE NOT NULL,
	`schedule_name` VARCHAR(50) NOT NULL,
	`time` TIME NOT NULL,
	CONSTRAINT `PK_schedules` PRIMARY KEY (`schedule_id` ASC)
)

;

CREATE TABLE `songs`
(
	`song_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`song_name` VARCHAR(50) NOT NULL,
	`box_id` INT UNSIGNED NOT NULL,
	`file` VARCHAR(255) NOT NULL,
	CONSTRAINT `PK_songs` PRIMARY KEY (`song_id` ASC)
)

;

CREATE TABLE `subscribers`
(
	`subs_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`subs_name` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_subscribers` PRIMARY KEY (`subs_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `schedules` 
 ADD INDEX `IXFK_schedules_prayers` (`prayer_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `box_subscribers` 
 ADD CONSTRAINT `FK_box_subscribers_boxes`
	FOREIGN KEY (`box_id`) REFERENCES `boxes` (`box_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `box_subscribers` 
 ADD CONSTRAINT `FK_box_subscribers_subscribers`
	FOREIGN KEY (`subs_id`) REFERENCES `subscribers` (`subs_id`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `boxes` 
 ADD CONSTRAINT `FK_boxes_box_parayers`
	FOREIGN KEY (`prayer_id`) REFERENCES `prayers` (`prayer_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `schedules` 
 ADD CONSTRAINT `FK_schedules_prayers`
	FOREIGN KEY (`prayer_id`) REFERENCES `prayers` (`prayer_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `songs` 
 ADD CONSTRAINT `FK_songs_boxes`
	FOREIGN KEY (`box_id`) REFERENCES `boxes` (`box_id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
